# Generated by Django 5.1.15 on 2026-04-28 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=8, unique=True)),
                ('sort_code', models.CharField(max_length=6)),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current Account'), ('SAVINGS', 'Savings Account'), ('JUNIOR', 'Junior Account')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
