# Generated by Django 5.1.15 on 2026-05-07 19:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_account_overdraft_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('daily_card_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('daily_blik_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='accounts.account')),
            ],
        ),
    ]
