# Generated by Django 5.1.15 on 2026-05-09 19:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_overdraft_limit_and_more'),
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('CARD', 'Card'), ('BLIK', 'Blik'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'channel')},
            },
        ),
        migrations.DeleteModel(
            name='AccountLimits',
        ),
    ]
