# Generated by Django 5.1.15 on 2026-05-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_overdraft_limit_and_more'),
        ('limits', '0002_accountlimit_delete_accountlimits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountLimit',
            new_name='AccountLimits',
        ),
    ]
