# Generated by Django 5.1.15 on 2026-05-16 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_overdraft_limit_and_more'),
        ('transfers', '0002_savedrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_account', models.CharField(max_length=34)),
                ('swift_bic', models.CharField(blank=True, max_length=11, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('title', models.CharField(max_length=255)),
                ('routing_method', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('junior_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junior_approvals', to=settings.AUTH_USER_MODEL)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
