# Generated by Django 5.1.15 on 2026-04-28 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INTERNAL', 'Internal Transfer'), ('BACS', 'Bacs Payment'), ('FPS', 'Faster Payments'), ('CHAPS', 'CHAPS Payment'), ('SWIFT', 'SWIFT Payment'), ('CARD', 'Card Payment'), ('BLIK', 'BLIK / Instant')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('PARENT_APPROVAL_REQUIRED', 'Awaiting Parent Approval')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account')),
            ],
        ),
    ]
