# Generated by Django 5.1.15 on 2026-05-09 21:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PHYSICAL', 'Physical'), ('PREPAID', 'Prepaid')], default='VIRTUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='full_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='prepaid_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('SHIPPING', 'Shipped'), ('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20),
        ),
    ]
